### PR TITLE
eliminate errors

### PR DESCRIPTION
**Pull request by gautschr**
- inavild geoname-values fixed
- text fromatting
- add audio example
- delete files in top folder

### CODE REVIEW

**Comment by jnussbaum** [comment]
Just two short comments:
 - Which version of the API do I need to create rosetta.json? I tried it with v17.0.0 (branch main), but it complains that `ArchiveRepresentation` is not valid. (I work with dsp-tools 1.6.1).
 - In rosetta.xml, the comment at the very top of the file contains an outdated link, which is forwarded to https://docs-api.dasch.swiss/03-apis/api-v2/reading-user-permissions/.

**Comment by jnussbaum** [comment]
Okay, I was able to upload it with dsp-tools on branch wip/dev-178-permissions-in-xml-upload. 

I have the following feedback:
 - `ERROR while trying to upload 'RosettaPDF' (doc_001). The error message was: Invalid time value! "2021-11-30T12:00:00"` 
You forgot the time zone, it must be: 2021-11-30T12:00:00+00:00
 - In rosetta.xml, the comment at the very top of the file contains an outdated link, which is forwarded to https://docs-api.dasch.swiss/03-apis/api-v2/reading-user-permissions/.
 - What is the sense of having a copy of the onto and the xml data files in the folder Documents?

That's all. Otherwise it's okay I think.

**Review by BalduinLandolt — APPROVED** [review]
apart from the things mentioned by Johannes it looks good to me

**Comment by gautschr** [comment]
@jnussbaum rosetta.xml and rosetta.json are part of the file rosetta.zip. All files which are contained in the zip-file are in this folder. I'll correct the two things you mention but will at the same time include already additional amendments in connection with permissions which I'm testing currently. I'll ask for a new review afterwards.

**Review by jnussbaum — APPROVED** [review]

**Pull request merged**
